config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :favorite_sports, only: [:create, :destroy]

  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: "pages#home"

  get "/dashboard/", to: "pages#dashboard"
  resources :events do
    resources :messages, only: [:create]
    resources :participations, only: [:destroy, :create]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible under-navbar" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible under-navbar" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <% if user_signed_in? %>
    <%= link_to dashboard_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "http://www.iconarchive.com/download/i65369/icons-land/metro-raster-sport/Soccer-Ball.ico" %>
    <% end %>
    <%else%>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "http://www.iconarchive.com/download/i65369/icons-land/metro-raster-sport/Soccer-Ball.ico" %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>


      <!-- Search form -->
      <%= render 'shared/search-bar' %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo %>
            <%=cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%=cl_image_tag "https://image.freepik.com/icones-gratuites/profil-de-l&-39;utilisateur-avatar_318-31071.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>



          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Your Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to events_path do %>
                <i class="fa fa-trophy"></i>  <%= t(".event", default: "Events") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login text link -->
      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn"%>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn" %>
    <% end %>
  </div>


  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
        <li> <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-bar-large.html.erb
<div class="search-bar form-inline" data-reactid=".0.0">
  <%= form_tag events_path, method: :get do %>
    <div class="form-group group-form">
      <%= label :sport, "Sport: ", class: "col-form-label col-form-label-sm" %>
      <%= select_tag :sport, options_from_collection_for_select(Sport.all, :id, :name) %>
    </div>
    <div class="form-group group-form">
      <%= label :address, "Events near: ", class: "col-form-label col-form-label-sm" %>
      <%= text_field_tag :address, params[:address], class: "form-control form-control-xs", placeholder: "City" %>
    </div>

    <div class="form-group group-form">
      <%= label :distance, "Distance: ", class: "col-form-label col-form-label-sm" %>
      <%= text_field_tag :distance, params[:distance], class: "form-control form-control-xs", placeholder: "5" %>
      <span>km&nbsp&nbsp</span>
    </div>

    <div class="form-group group-form">
      <%= label :date, "Date", class: "col-form-label col-form-label-sm" %>
      <%= date_field_tag :date, params[:date], class: "form-control form-control-xs", placeholder: Date.today.to_s %>
    </div>

    <%= submit_tag "Search", class: "btn btn-default" %>
  <% end %>
</div>

app/views/shared/_search-bar.html.erb
<div class="search-bar form-inline" data-reactid=".0.0">
  <%= form_tag events_path, method: :get do %>
    <div class="form-group group-form">
      <%= label :sport, "Sport: ", class: "col-form-label col-form-label-sm" %>
      <%= select_tag :sport, options_from_collection_for_select(Sport.all, :id, :name) %>
    </div>
    <div class="form-group group-form">
      <%= label :address, "Events near: ", class: "col-form-label col-form-label-sm" %>
      <%= text_field_tag :address, params[:address], class: "form-control form-control-xs", placeholder: "City" %>
    </div>

    <div class="form-group group-form">
      <%= label :date, "Date", class: "col-form-label col-form-label-sm" %>
      <%= date_field_tag :date, params[:date], class: "form-control form-control-xs", placeholder: Date.today.to_s %>
    </div>
    <%= submit_tag "Search", class: "btn btn-default" %>
  <% end %>
</div>