config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :favorite_sports, only: [:create, :destroy]

  root to: "pages#dashboard", constraints: lambda { |r| r.env["warden"].authenticate? }
  root to: "pages#home"

  get "/dashboard/", to: "pages#dashboard"
  resources :events do
    resources :messages, only: [:create]
    resources :participations, only: [:destroy, :create]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount Attachinary::Engine => "/attachinary"
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  # belongs_to :place
  belongs_to :sport
  has_many :participations, dependent: :destroy
  has_many :messages

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :required_level, presence: true
  #validates :status, presence: true
  validates :required_material, presence: true
  validates :sport, presence: true
  validates :date, presence: true
  validates :address, presence: true
  validates :number_of_players, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    #sport = Sport.find_by_name("soccer")#params[sport])
    #@events = Event.where({ sport: sport})

    if research_params[:address].present?
      if research_params[:distance].present?
        activities = Event.near(research_params[:address], research_params[:distance])
      else
        activities = Event.near(research_params[:address], 100 )
      end
    else
      activities = Event.all
    end

    if research_params[:date].present?
      date = Date.parse(research_params[:date])
    else
      date = Date.today
    end

    @events = activities.select { |activity| activity.sport.id == (research_params[:sport]).to_i && activity.date == date }
    e = research_params
    #raise
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow render_to_string(partial: "/events/map_box", locals: { event: event })
    end
  end

  def show
    @participant = Participation.new
    @message = Message.new
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow render_to_string(partial: "/events/map_box", locals: { event: event })
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      Participation.create(status: "organizer", user: current_user, event: @event)
      redirect_to @event
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    @event.save
    redirect_to @event
  end

  def new
    @event = Event.new
  end


  private

  def event_params
    params.require(:event).permit(:name,
                                  :required_level,
                                  :required_material,
                                  :description,
                                  :number_of_players,
                                  :status,
                                  :date,
                                  :time,
                                  :address,
                                  :sport_id
                                  )
  end

  def research_params
    params.permit(:address,
                                  :date,
                                  :distance,
                                  :sport
                                  )
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :required_level %>
  <%= f.input :required_material %>
  <%= f.input :description %>
  <%= f.input :number_of_players %>
  <%= f.input :date %>
  <%= f.input :time %>
  <%= f.input :address %>
  <%= f.association :sport %>
  <%= f.submit %>
<% end %>

app/views/events/_map_box.html.erb
<h3>
  <%= link_to event.name, event %>
</h3>
<%= link_to (cl_image_tag event.sport.photo.path, width: 150, height: 100, crop: :fill), event %>

<p>
  <%= event.time.strftime("%m/%d/%Y") %>
  <%= event.time.strftime("at %I:%M%p") %>
</p>

app/views/events/_messaging.html.erb
<br>
<hr>
<ul>
  <% @event.messages.each do |message| %>
  <li>
    <%= "#{message.participation.user.first_name}: #{message.content}" %>
  </li>
  <% end %>
</ul>

<%= simple_form_for([@event, @message]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="under-navbar">
<h1>Edit</h1>

<%= render "form" %>
</div>
</div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="under-navbar">
<%= render "shared/search-bar-large" %>

  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="row">
          <% @events.each do |event| %>
            <div class="col-md-6">
              <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= cl_image_path event.sport.photo.path, width: 300, height: 200, crop: :fill %>);" alt="Photo de Sport">

                  <%= image_tag("https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAXTAAAAJDFjYzM5MDMzLTI2MjYtNDliZS1hYTJlLTRiYjcyZjczYzRmMw.jpg", class: "card-user avatar avatar-large")%>
                  <h2 class="card-title"><%= event.name %></h2>
                  <h3 class="card-subtitle"></h3>
                  <p class="card-description"><%= event.user.first_name %> <%= event.user.last_name %><%= event.description %></p>
                  <%= link_to "", event, class: "card-link" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6">
        <div id="map" style="width: 100%; height: 100vh;">
          <% content_for(:after_js) do %>
            <script>
              $(document).ready(function() {
                var handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' } }, function() {
                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  if (markers.length == 0) {
                    handler.getMap().setZoom(2);
                  } else if (markers.length == 1) {
                    handler.getMap().setZoom(15);
                  }
                });
              });
            </script>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <p class="btn btn-default">
  <%= link_to "Create a event", new_event_path %>
  </p>
</div>
</div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="under-navbar">
<h1>New</h1>

<%= render "form" %>
</div>
</div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="under-navbar">
      <%= cl_image_tag @event.sport.photo.path, class: "card" %>
      <h1><%= @event.name %></h1>
      <p><%= @event.description %></p>

      <%= link_to "Edit", edit_event_path(@event) %>
      <%= link_to "Delete", event_path(@event), method: "delete", data: { confirm: "Are you sure SURE?" } %>



      <% @event.participations.each do |participant|%>
        <%= participant.user.first_name %>
        <%= participant.user.last_name %>

        <p>--</p>

        <%= participant.status %>
      <% end %>

      <%= "#{@event.participations.count} / #{@event.number_of_players}" %>

      <div id="map" style="width: 100%; height: 500px;">
        <% content_for(:after_js) do %>
          <script>
            $(document).ready(function() {
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(15);
                }
              });
            });
          </script>
        <% end %>
      </div>

      <% if @event.participations.find_by_user_id(current_user.id) %>
        <%= render "messaging" %>
        <%= link_to "Cancel", event_participation_path([@event, @event.participations.find_by_user_id(current_user.id)]), method: "delete", data: { confirm: "Are you sure SURE?" } %>
      <% else %>
        <%= link_to "Attend", event_participations_path(@event), method: "post", class: "btn btn-success" %>
      <% end %>
      <%= link_to "Back to your profile", dashboard_path(@event), class: "btn btn-default" %>
    </div>
  </div>
</div>